[package]
name = "interacting"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoincore-rpc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = {workspace = true}
